 - name: Install Kibana
   ansible.builtin.apt:
    update-cache: yes
    name: kibana
 - name: Configure Kibana
   lineinfile:
    path: /etc/kibana/kibana.yml
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
   loop:
    - regexp: "elasticsearch.hosts"
      line: 'elasticsearch.hosts: ["http://{{ elastic_host }}:9200"]'
 - name: Start Kibana Service on port 5601
   ansible.builtin.systemd:
    name: kibana.service
    state: started