---
# tasks file for ELK
#install elastic on a remote ec2 instance

#  - name: Installation
#    tags: install
#    import_tasks: install.yml
  - name: Elasticsearch Run
    tags: run
    import_tasks: elastic_run.yml

