 - name: Install Logstash
   ansible.builtin.apt:
    name: logstash
    update-cache: yes
 - name: Alter Logstash Configuration
   lineinfile:
    path: /etc/logstash/jvm.options
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
   loop:
    - regexp: "Xmx1G"
      line:  "-Xmx128m"
    - regexp: "Xms1G"
      line: '-Xms128m'
 - name: Enable Logstash
   ansible.builtin.systemd:
    name: logstash
    enabled: true
 - name: Confuring Logstash
   template:
    src: templates/etc/logstash/conf.d/beats.conf.j2
    dest: /etc/logstash/conf.d/beats.conf
 - name: Making /usr/share/logstash/data is writable
   file:
    path: /usr/share/logstash/data
    owner: "van"
    group: "van"
