services:
  jenkins:
    image: jenkins/jenkins # :latest (weekly), :lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:

    # FYI https://www.jenkins.io/doc/book/installing/docker/