 - name: Install Elastic Search
   ansible.builtin.apt:
    update-cache: yes
    name: elasticsearch
 - name: Alter Elasticsearch Configuration
   lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
   loop:
    - regexp: '#cluster.name: my-application'
      line: 'cluster.name: ec2_monitoring'
    - regexp: '#node.name: node-1'
      line: 'node.name: ec2_es1'
    - regexp: '#network.host'
      line: "network.host: 0.0.0.0"
    - regexp: '#cluster.initial_master_nodes'
      line: "cluster.initial_master_nodes:  ec2_es1"
 - name: Adding jvm.options.d
   file:
    path: files/etc/elasticsearch/jvm.options.d
    dest: /etc/elasticsearch/jvm.options.d/
 - name: Configure vm.max_map_count
   sysctl: name={{ item.key }} value={{ item.value }}
   with_items:
    - {key: "vm.max_map_count", value: "262144"}
 - name: Start Elasticsearch on Port 9200
   ansible.builtin.systemd:
    name: elasticsearch.service
    state: started