  - name: Update
    ansible.builtin.apt:
     update_cache: yes
  - name: Check for Appropriate Certificates
    ansible.builtin.apt:
      name: ca-certificates
      state: present
  - name: Install Java
    ansible.builtin.apt:
      name: openjdk-17-jre
      state: present