   - name: Taking Jenkins Key
     ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      state: present
   - name: Downloading from Repository
     ansible.builtin.apt_repository:
      repo: "deb https://pkg.jenkins.io/debian-stable binary/"
      state: present
   - name: Install Jenkins
     ansible.builtin.apt:
      name: jenkins
      state: present
      update-cache: true
   - name: Enabling Jenkins services
     ansible.builtin.systemd:
      name: jenkins
      enabled: true
   - name: Running Jenkins on Port 8080
     ansible.builtin.systemd:
      name: jenkins
      state: started